Fix redis host resolution
3scale/apicast-xc pull request #18
Opened 2017-03-24 18:48 UTC by mayorova

Close #12

2017-03-24 18:51 UTC, mayorova commented
As a further improvement I'd suggest reusing APIcast's function from [threescale_utils](https://github.com/3scale/apicast/blob/v3.0.0-beta3/apicast/src/threescale_utils.lua#L123), as it works with full Redis URL, with authorization and DB. But it's better to extract it to a separate module first.

2017-03-27 09:04 UTC, davidor commented
I don't think that deleting the part of the code that overrides `header_filter` and `body_filter` is a good idea.
```
_M.header_filter = function() end		
_M.body_filter = function() end
```

That part of the code documents explicitly that XC does not want to perform any work in any of those 2 phases. If we delete that, every time that Apicast releases a new version, we will need to check whether it added new things in any of those two methods.

2017-03-27 09:13 UTC, davidor commented on xc/cache.lua
> +    ngx.log(ngx.WARN, "[cache] couldn't connect to redis: ", err)
We should log a similar error in `_M.report`.

2017-03-27 09:16 UTC, davidor commented on xc/cache.lua
> +    ngx.log(ngx.WARN, "[cache] couldn't connect to redis: ", err)
If we do, we should change this error message to a more specific one, so the user knows whether the error happened while authorizing or while reporting.

2017-03-27 09:17 UTC, mayorova commented
@davidor OK, agreed re: `header_filter` and `body_filter`, I'll jus remove this commit from the PR

2017-03-27 09:28 UTC, davidor commented on xc/cache.lua
> +    ngx.log(ngx.WARN, "[cache] couldn't connect to redis: ", err)
Also, we should add a test that checks that we log a warning when there's an error connecting to Redis.
That test should be under this describe clause: `describe('when there is an error acquiring a Redis connection', function()` in `cache_spec.lua`.

2017-03-27 09:29 UTC, davidor commented on xc/priority_auths.lua
> +    ngx.log(ngx.WARN, "[priority auths] couldn't connect to redis pub: ", err)
I was going to say that we need tests for this too. However, I realized that `priority_auths` has no tests. That's homework for me and @unleashed :D

2017-03-27 09:42 UTC, davidor commented on .busted
> +return {
We are currently sending the options in the `script/test` file, but I like the idea of using this file for clarity.
Apart from that, is the `lpath` option needed?

2017-03-27 09:42 UTC, davidor commented on .busted
> +}
Missing newline.

2017-03-27 09:43 UTC, davidor commented on spec/spec_helper.lua
> +end)
Missing newline.

2017-03-27 09:47 UTC, mayorova commented on .busted
> +return {
I just stole this from APIcast :) https://github.com/3scale/apicast/blob/master/.busted
No idea how it works, to be honest.

2017-03-27 09:55 UTC, davidor commented on xc/priority_auths.lua
> +    ngx.log(ngx.WARN, "[priority auths] couldn't connect to redis pub: ", err)
All these calls look the same: `ngx.log(ngx.WARN, error_prefix, err)`. How about extracting a `log_warning(error_prefix, err)` local method or something similar?

Also, I think that extracting all these error prefixes to a local constant would improve readability. Something like: `local errors = { redis_pub_connect: "[priority_auths] couldn't connect to redis pub: ", redis_sub_connect: "...", ... }`

What do you think?

2017-03-27 15:29 UTC, mayorova commented on xc/cache.lua
> +    ngx.log(ngx.WARN, "[cache] couldn't connect to redis: ", err)
@davidor Can you help with the test please?

2017-03-27 15:31 UTC, mayorova commented on xc/priority_auths.lua
> +    ngx.log(ngx.WARN, "[priority auths] couldn't connect to redis pub: ", err)
To me it looks like overcomplicating the things a bit.
Also, for troubleshooting, I actually find it useful to just take the error message found in the logs, and search for where it appears in the code - makes it easy to trace the issue.

2017-03-27 15:57 UTC, davidor commented on xc/cache.lua
> +    ngx.log(ngx.WARN, "[cache] couldn't connect to redis: ", err)
Sure, I'll take care of that

2017-03-28 09:42 UTC, davidor commented on xc/priority_auths.lua
> +    ngx.log(ngx.WARN, "[priority auths] couldn't connect to redis pub: ", err)
It's OK for now, but later we might want to refactor this and extract parts of the logging functionality to its own module.

2017-03-28 10:30 UTC, unleashed commented on xc/redis_pool.lua
> +  local ok, err = conn:connect(threescale_utils.resolve(_M.host, _M.port))
can't this fail? if it does, it just blows up the request?

2017-03-28 10:30 UTC, davidor commented
@daria : I squashed your third commit as it was only fixing things introduced in the second commit. I also deleted `spec_helper.lua` and `.busted` as they are not needed because of the way I tested the logging part in the commit I added.

2017-03-28 10:30 UTC, unleashed commented on xc/redis_pool.lua
> +  local ok, err = conn:connect(threescale_utils.resolve(_M.host, _M.port))
I mean the resolving in particular.

2017-03-28 10:36 UTC, davidor commented on xc/redis_pool.lua
> +  local ok, err = conn:connect(threescale_utils.resolve(_M.host, _M.port))
Good point. We should check this.

2017-03-29 13:24 UTC, davidor commented on xc/redis_pool.lua
> +  local ok, err = conn:connect(threescale_utils.resolve(_M.host, _M.port))
I implemented some error handling and tested it. Check the 2 new commits that I added.

2017-03-29 14:08 UTC, unleashed commented
The `ngx.log` directives are basically actively fought against. Logging is something that calling code should handle. That's why we have a mechanism for notifying errors to callers. In fact, some log calls are placed right after specifying in comments that errors are returned in a return parameter.

Now admittedly the mechanism is probably not being used in all places that it should be, and some errors are recoverable and this is not taken into account (or because they are recoverable, information that would be good to have is lost, ie. if cache fails to contact Redis but somehow later priority auth works).

I think using the error reporting mechanism we have here will not solve all needs, especially if we want warnings and not hard errors, so either we put this on hold or we commit to reviewing the mechanism and clean these calls later on.

Such a mechanism could be a function for log information (including log level and potentially callsite info, no matter whether actual logging is performed at that time or later) and/or adding more information to the errors entry in the returned data to account for that extra information from non-fatal circumstances.

Either way the rest of the PR looks good.

2017-03-29 14:20 UTC, unleashed requested changes
Sorry, blocking until the performance regression caused by resolving is fixed. Resolving should not be a perf regression if proper TTL handling is done.

Edit: @davidor to make sure there is no such regression.
Edit2: no performance regression! 👍

2017-03-29 18:24 UTC, davidor commented
I agree @unleashed . I think we should review the logging mechanism. However, the log calls that @mayorova added can be useful when debugging. So I think we can merge this to give something to our users until we implement a better logging mechanism with the characteristics that you described in your comment.

Regarding the performance regression, I'll run some tests tomorrow to be sure.

2017-03-30 09:52 UTC, davidor approved these changes
It works well :+1:

2017-03-30 10:12 UTC, unleashed approved these changes

2017-03-30 10:12 UTC, merged